---
output: html_document
editor_options: 
  chunk_output_type: console
---


<pre>
# Callin Switzer
# Jan 18 2019

# Make an oscillogram in R (show time vs. sound)
# 
# Make spectrogram (shows frequency vs. time)
# 
# Make a zoomed-in view of a portion of the sound

</pre>



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r, warning = FALSE, message=FALSE}
# install packages
ipak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if(length(new.pkg)) install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
}

packages <- c("tidyverse", "tuneR", "signal", "seewave")
ipak(packages)

# set ggplot theme
theme_set(theme_classic() + 
            theme(axis.text=element_text(colour="black"), 
                  text=element_text(size=10)))

# set  directories
dataDir <- file.path(getwd(), "data")
figDir <- file.path(getwd(), "figures")

print(paste("last run ", Sys.time()))
print(R.version)
```


# Define spiky signal smoother function
```{r}
spikySignalSmoother_rollingMean = function(spikySignal = y, sampFreq = sampFreq, freqOfInterest = 3, 
                                           highPassFiltFreq = 50){
  # Makes a smooth waveform with the same frequency as
  # the spiky signal
  #
  # Args:
  #   spikySignal: Spiky signal to be smoothed
  #   sampFreq: The sampling frequency of the spiky signal
  #   freqOfInterest: A rough guess at the minimum frequency you're interested in resolving.
  #
  # Returns:
  #   A smoother signal with the same length as the original spiky signal
  
  periodForFOI = sampFreq / freqOfInterest / 2
  
  # defineFilter
  filteredData <- zoo::rollmean(abs(spikySignal), k = periodForFOI )
  
  # rescale
  scaledFilteredData <- (filteredData-min(filteredData))/(max(filteredData)-min(filteredData)) * 2 - 1
  
  nyqFreq = sampFreq / 2
  
  bf = signal::butter(6, W = highPassFiltFreq / nyqFreq, type = "high")
  filteredData_F <- signal::filtfilt(bf, scaledFilteredData)
  
  return(filteredData_F)
}



```



```{r}
# define sound
wavFle = file.path(dataDir, "Protandrena906 copy.wav")


# load sound
w1 <- readWave(wavFle) #, from = 3, to = 3.4, units = "seconds")
sampRate = w1@samp.rate
nyqFreq = sampRate / 2

# first highpass filter
highpassFreq = 5000 # hz

# convert to mono
if(w1@stereo){
  w1 <- mono(w1, "left")
}

w2 <- w1@left

plot(w2, type = 'l')

# high-pass filter
bf = signal::butter(6, W = highpassFreq / nyqFreq, type = "high")
b1 <- signal::filtfilt(bf, w2)
## listen(b1, f = sampRate)

plot(b1, type = 'l')

# convert spiky signal to smooth signal

b2 <- spikySignalSmoother_rollingMean(b1, sampFreq = sampRate, freqOfInterest = 300)

plot(b2, type = "l")


# view fundamental frequency over time: 
# with 50% overlap between successive sliding windows, time zoom and 
# amplitude filter (threshold)
# overlaid on a spectrogram
spectro(b2, f=sampRate, ovlp=50, zp=16, wl = 2**13,
        scale=FALSE, palette=reverse.gray.colors.2, flim = c(0, 1), 
        main = paste0(basename(wavFle), " starting at ", 0, " seconds"), 
        osc = TRUE)

```


```{r}
# load sound
wavFle = file.path(dataDir, "STE-017 copy.wav")


# load sound
recStart = 53
w1 <- readWave(wavFle, from = recStart, to = 64.7, units = "sec")
sampRate = w1@samp.rate
nyqFreq = sampRate / 2

# first highpass filter
highpassFreq = 5000 # hz

# convert to mono
if(w1@stereo){
  w1 <- mono(w1, "left")
}

w2 <- w1@left

plot(w2[seq(0, length(w2), length.out = 100000)], type = 'l')

# high-pass filter
bf = signal::butter(6, W = highpassFreq / nyqFreq, type = "high")
b1 <- signal::filtfilt(bf, w2)
# listen(b1, f = sampRate)

plot(b1, type = 'l')

# convert spiky signal to smooth signal
b2 <- spikySignalSmoother_rollingMean(b1, sampFreq = sampRate, freqOfInterest = 150)

# plot(b2, type = "l")


# view fundamental frequency over time: 
spectro(b2, f=sampRate, ovlp=50, zp=16, wl = 2**13,
        scale=FALSE, palette=reverse.gray.colors.2, flim = c(0, 1), 
        osc = TRUE, 
        main = paste0(basename(wavFle), " starting at ", recStart, " seconds"), 
        tlab = paste0("Time (s) past ", recStart, " seconds"))


png(file.path(figDir, "STE-017_53-63_sec.png"), width = 6.5, height = 5, units = "in", 
    res = 200)

spectro(b2, f=sampRate, ovlp=50, zp=16, wl = 2**13,
        scale=FALSE, palette=reverse.gray.colors.2, flim = c(0, 1), 
        osc = TRUE, 
        main = paste0(basename(wavFle), " starting at ", recStart, " seconds"), 
        tlab = paste0("Time (s) past ", recStart, " seconds"))

dev.off()

```




```{r}
# load sound
wavFle = file.path(dataDir, "STE-005 copy.wav")


# load sound
recStart = 35 
recEnd = 43.6
w1 <- readWave(wavFle, from = recStart, to = recEnd, units = "sec")
sampRate = w1@samp.rate
nyqFreq = sampRate / 2


# first highpass filter
highpassFreq = 5000 # hz

# convert to mono
if(w1@stereo){
  w1 <- mono(w1, "left")
}

w2 <- w1@left
# listen(w2, f= sampRate)

#plot(w2[seq(0, length(w2), length.out = 100000)], type = 'l')

# high-pass filter
bf = signal::butter(6, W = highpassFreq / nyqFreq, type = "high")
b1 <- signal::filtfilt(bf, w2)
# listen(b1, f = sampRate)

#plot(b1, type = 'l')

# convert spiky signal to smooth signal
b2 <- spikySignalSmoother_rollingMean(b1, sampFreq = sampRate, freqOfInterest = 150)

#plot(b2, type = "l")


# view fundamental frequency over time: 

spectro(b2, f=sampRate, ovlp=50, zp=16, wl = 2**13,
        scale=FALSE, palette=reverse.gray.colors.2, flim = c(0, .7), 
        osc = TRUE, main = paste0(basename(wavFle), " starting at ", recStart, " seconds"))

png(file.path(figDir, "STE-005_35-44_sec.png"), width = 6.5, height = 5, units = "in", 
    res = 200)

spectro(b2, f=sampRate, ovlp=50, zp=16, wl = 2**13,
        scale=FALSE, palette=reverse.gray.colors.2, flim = c(0, 0.7), 
        osc = TRUE, 
        main = paste0(basename(wavFle), " starting at ", recStart, " seconds"), 
        tlab = paste0("Time (s) past ", recStart, " seconds"))

dev.off()
```




```{r}
# load sound
wavFle = file.path(dataDir, "STE-004 copy.wav")


# load sound
recStart = 6
recEnd = 11
w1 <- readWave(wavFle, from = recStart, to = recEnd, units = "sec")
sampRate = w1@samp.rate
nyqFreq = sampRate / 2


# first highpass filter
highpassFreq = 5000 # hz

# convert to mono
if(w1@stereo){
  w1 <- mono(w1, "left")
}

w2 <- w1@left
# listen(w2, f= sampRate)

#plot(w2[seq(0, length(w2), length.out = 100000)], type = 'l')

# high-pass filter
bf = signal::butter(6, W = highpassFreq / nyqFreq, type = "high")
b1 <- signal::filtfilt(bf, w2)
# listen(b1, f = sampRate)

#plot(b1, type = 'l')

# convert spiky signal to smooth signal
b2 <- spikySignalSmoother_rollingMean(b1, sampFreq = sampRate, freqOfInterest = 150)

#plot(b2, type = "l")


# view fundamental frequency over time: 
# with 50% overlap between successive sliding windows, time zoom and 
# amplitude filter (threshold)
# overlaid on a spectrogram
spectro(b2, f=sampRate, ovlp=50, zp=16, wl = 2**13,
        scale=FALSE, palette=reverse.gray.colors.2, flim = c(0, 1), 
        osc = TRUE, main = paste0(basename(wavFle), " starting at ", recStart, " seconds"))

png(file.path(figDir, "STE-006_06-11_sec.png"), width = 6.5, height = 5, units = "in", 
    res = 200)

spectro(b2, f=sampRate, ovlp=50, zp=16, wl = 2**13,
        scale=FALSE, palette=reverse.gray.colors.2, flim = c(0, 0.7), 
        osc = TRUE, 
        main = paste0(basename(wavFle), " starting at ", recStart, " seconds"), 
        tlab = paste0("Time (s) past ", recStart, " seconds"))

dev.off()

```


```{r}
# load sound
wavFle = file.path(dataDir, "STE-020 copy.wav")


# load sound
recStart = 114
recEnd = 130
w1 <- readWave(wavFle, from = recStart, to = recEnd, units = "sec")
sampRate = w1@samp.rate
nyqFreq = sampRate / 2


# first highpass filter
highpassFreq = 5000 # hz

# convert to mono
if(w1@stereo){
  w1 <- mono(w1, "left")
}

w2 <- w1@left
# listen(w2, f= sampRate)

#plot(w2[seq(0, length(w2), length.out = 100000)], type = 'l')

# high-pass filter
bf = signal::butter(6, W = highpassFreq / nyqFreq, type = "high")
b1 <- signal::filtfilt(bf, w2)
# listen(b1, f = sampRate)

#plot(b1, type = 'l')

# convert spiky signal to smooth signal
b2 <- spikySignalSmoother_rollingMean(b1, sampFreq = sampRate, freqOfInterest = 150)

#plot(b2, type = "l")


# view fundamental frequency over time: 
spectro(b2, f=sampRate, ovlp=50, zp=16, wl = 2**13,
        scale=FALSE, palette=reverse.gray.colors.2, flim = c(0, 1), 
        osc = TRUE, main = paste0(basename(wavFle), " starting at ", recStart, " seconds"))

png(file.path(figDir, "STE-020_114-130_sec.png"), width = 6.5, height = 5, units = "in", 
    res = 200)

spectro(b2, f=sampRate, ovlp=50, zp=16, wl = 2**13,
        scale=FALSE, palette=reverse.gray.colors.2, flim = c(0, 0.7), 
        osc = TRUE, 
        main = paste0(basename(wavFle), " starting at ", recStart, " seconds"), 
        tlab = paste0("Time (s) past ", recStart, " seconds"))

dev.off()

```


# Make a figure outlining the process
```{r}

# load sound
wavFle = file.path(dataDir, "STE-020 copy.wav")


# load sound
recStart = 116.5
recEnd = 119
w1 <- readWave(wavFle, from = recStart, to = recEnd, units = "sec")
sampRate = w1@samp.rate
nyqFreq = sampRate / 2


# first highpass filter
highpassFreq = 5000 # hz

# convert to mono
if(w1@stereo){
  w1 <- mono(w1, "left")
}

w2 <- w1@left
listen(w2, f= sampRate)

png(file.path(figDir, "Process.png"), width = 8, height = 8, res = 200, units = "in")
par(mfrow = c(3, 2))

plot(w2, type = 'l', ylab = "", main = "original sound")

# high-pass filter
bf = signal::butter(6, W = highpassFreq / nyqFreq, type = "high")
b1 <- signal::filtfilt(bf, w2)
#listen(b1, f = sampRate)

plot(b1, type = 'l', ylab = "", main = "highpass filtered (>5000 Hz) sound")
polygon(x = c(4e04, 4e04, 4.5e04, 4.5e04), 
        y = c(-500, 500, 500, -500), border = NA,
        col = rgb(1,0.1, 0.5,0.5) )

plot(b1, type = 'l', ylab = "", main = "highpass filtered (>5000 Hz) sound, zoomed", 
     x = (1:length(b1)) / sampRate,
     xlim =c(sampRate,sampRate + 0.1*sampRate) / sampRate , xlab = "Time (s)")
spec(w2, f = sampRate, flim = c(0, 0.5))

# convert spiky signal to smooth signal
b2 <- spikySignalSmoother_rollingMean(b1, sampFreq = sampRate, freqOfInterest = 150)


plot(b2, type = 'l', ylab = "", main = "smoothed signal", 
     x = (1:length(b2)) / sampRate,
     xlim =c(sampRate,sampRate + 0.1*sampRate) / sampRate , xlab = "Time (s)")
spec(b2, f = sampRate, flim = c(0, 0.5))

dev.off()

# view fundamental frequency over time: 
spectro(b2, f=sampRate, ovlp=50, zp=16, wl = 2**13,
        scale=FALSE, palette=reverse.gray.colors.2, flim = c(0, 1), 
        osc = TRUE, main = paste0(basename(wavFle), " starting at ", recStart, " seconds"))


```

